//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVN.HCMC.WebAPI.DataProvider.WGISService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhanQuyen", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PhanQuyen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ReadField;
        
        private bool CreateField;
        
        private bool UpdateField;
        
        private bool DeleteField;
        
        private bool EnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DonViField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Read {
            get {
                return this.ReadField;
            }
            set {
                if ((this.ReadField.Equals(value) != true)) {
                    this.ReadField = value;
                    this.RaisePropertyChanged("Read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool Create {
            get {
                return this.CreateField;
            }
            set {
                if ((this.CreateField.Equals(value) != true)) {
                    this.CreateField = value;
                    this.RaisePropertyChanged("Create");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Update {
            get {
                return this.UpdateField;
            }
            set {
                if ((this.UpdateField.Equals(value) != true)) {
                    this.UpdateField = value;
                    this.RaisePropertyChanged("Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Delete {
            get {
                return this.DeleteField;
            }
            set {
                if ((this.DeleteField.Equals(value) != true)) {
                    this.DeleteField = value;
                    this.RaisePropertyChanged("Delete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Enable {
            get {
                return this.EnableField;
            }
            set {
                if ((this.EnableField.Equals(value) != true)) {
                    this.EnableField = value;
                    this.RaisePropertyChanged("Enable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DonVi {
            get {
                return this.DonViField;
            }
            set {
                if ((object.ReferenceEquals(this.DonViField, value) != true)) {
                    this.DonViField = value;
                    this.RaisePropertyChanged("DonVi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WGISService.wsGISSoap")]
    public interface wsGISSoap {
        
        // CODEGEN: Generating message contract since element name pUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserUngDung", ReplyAction="*")]
        EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponse CheckUserUngDung(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserUngDung", ReplyAction="*")]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponse> CheckUserUngDungAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest request);
        
        // CODEGEN: Generating message contract since element name pUsername from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPhanQuyen", ReplyAction="*")]
        EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponse CheckPhanQuyen(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckPhanQuyen", ReplyAction="*")]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponse> CheckPhanQuyenAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserOutlook", ReplyAction="*")]
        EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponse CheckUserOutlook(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserOutlook", ReplyAction="*")]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponse> CheckUserOutlookAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAccountOutlookResult", ReplyAction="*")]
        EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponse IsAccountOutlookResult(EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAccountOutlookResult", ReplyAction="*")]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponse> IsAccountOutlookResultAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserUngDungRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserUngDung", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequestBody Body;
        
        public CheckUserUngDungRequest() {
        }
        
        public CheckUserUngDungRequest(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserUngDungRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pTenUngdung;
        
        public CheckUserUngDungRequestBody() {
        }
        
        public CheckUserUngDungRequestBody(string pUsername, string pTenUngdung) {
            this.pUsername = pUsername;
            this.pTenUngdung = pTenUngdung;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserUngDungResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserUngDungResponse", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponseBody Body;
        
        public CheckUserUngDungResponse() {
        }
        
        public CheckUserUngDungResponse(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserUngDungResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckUserUngDungResult;
        
        public CheckUserUngDungResponseBody() {
        }
        
        public CheckUserUngDungResponseBody(string CheckUserUngDungResult) {
            this.CheckUserUngDungResult = CheckUserUngDungResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPhanQuyenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPhanQuyen", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequestBody Body;
        
        public CheckPhanQuyenRequest() {
        }
        
        public CheckPhanQuyenRequest(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPhanQuyenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pTenUngdung;
        
        public CheckPhanQuyenRequestBody() {
        }
        
        public CheckPhanQuyenRequestBody(string pUsername, string pTenUngdung) {
            this.pUsername = pUsername;
            this.pTenUngdung = pTenUngdung;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPhanQuyenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckPhanQuyenResponse", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponseBody Body;
        
        public CheckPhanQuyenResponse() {
        }
        
        public CheckPhanQuyenResponse(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckPhanQuyenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.PhanQuyen CheckPhanQuyenResult;
        
        public CheckPhanQuyenResponseBody() {
        }
        
        public CheckPhanQuyenResponseBody(EVN.HCMC.WebAPI.DataProvider.WGISService.PhanQuyen CheckPhanQuyenResult) {
            this.CheckPhanQuyenResult = CheckPhanQuyenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserOutlookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserOutlook", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequestBody Body;
        
        public CheckUserOutlookRequest() {
        }
        
        public CheckUserOutlookRequest(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserOutlookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public CheckUserOutlookRequestBody() {
        }
        
        public CheckUserOutlookRequestBody(string Username, string password) {
            this.Username = Username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserOutlookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserOutlookResponse", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponseBody Body;
        
        public CheckUserOutlookResponse() {
        }
        
        public CheckUserOutlookResponse(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserOutlookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserOutlookResult;
        
        public CheckUserOutlookResponseBody() {
        }
        
        public CheckUserOutlookResponseBody(bool CheckUserOutlookResult) {
            this.CheckUserOutlookResult = CheckUserOutlookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAccountOutlookResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAccountOutlookResult", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequestBody Body;
        
        public IsAccountOutlookResultRequest() {
        }
        
        public IsAccountOutlookResultRequest(EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAccountOutlookResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public IsAccountOutlookResultRequestBody() {
        }
        
        public IsAccountOutlookResultRequestBody(string Username, string password) {
            this.Username = Username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAccountOutlookResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAccountOutlookResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponseBody Body;
        
        public IsAccountOutlookResultResponse() {
        }
        
        public IsAccountOutlookResultResponse(EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAccountOutlookResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsAccountOutlookResultResult;
        
        public IsAccountOutlookResultResponseBody() {
        }
        
        public IsAccountOutlookResultResponseBody(bool IsAccountOutlookResultResult) {
            this.IsAccountOutlookResultResult = IsAccountOutlookResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsGISSoapChannel : EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsGISSoapClient : System.ServiceModel.ClientBase<EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap>, EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap {
        
        public wsGISSoapClient() {
        }
        
        public wsGISSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsGISSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGISSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsGISSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponse EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.CheckUserUngDung(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest request) {
            return base.Channel.CheckUserUngDung(request);
        }
        
        public string CheckUserUngDung(string pUsername, string pTenUngdung) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequestBody();
            inValue.Body.pUsername = pUsername;
            inValue.Body.pTenUngdung = pTenUngdung;
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponse retVal = ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).CheckUserUngDung(inValue);
            return retVal.Body.CheckUserUngDungResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponse> EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.CheckUserUngDungAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest request) {
            return base.Channel.CheckUserUngDungAsync(request);
        }
        
        public System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungResponse> CheckUserUngDungAsync(string pUsername, string pTenUngdung) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserUngDungRequestBody();
            inValue.Body.pUsername = pUsername;
            inValue.Body.pTenUngdung = pTenUngdung;
            return ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).CheckUserUngDungAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponse EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.CheckPhanQuyen(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest request) {
            return base.Channel.CheckPhanQuyen(request);
        }
        
        public EVN.HCMC.WebAPI.DataProvider.WGISService.PhanQuyen CheckPhanQuyen(string pUsername, string pTenUngdung) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequestBody();
            inValue.Body.pUsername = pUsername;
            inValue.Body.pTenUngdung = pTenUngdung;
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponse retVal = ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).CheckPhanQuyen(inValue);
            return retVal.Body.CheckPhanQuyenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponse> EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.CheckPhanQuyenAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest request) {
            return base.Channel.CheckPhanQuyenAsync(request);
        }
        
        public System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenResponse> CheckPhanQuyenAsync(string pUsername, string pTenUngdung) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckPhanQuyenRequestBody();
            inValue.Body.pUsername = pUsername;
            inValue.Body.pTenUngdung = pTenUngdung;
            return ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).CheckPhanQuyenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponse EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.CheckUserOutlook(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest request) {
            return base.Channel.CheckUserOutlook(request);
        }
        
        public bool CheckUserOutlook(string Username, string password) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.password = password;
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponse retVal = ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).CheckUserOutlook(inValue);
            return retVal.Body.CheckUserOutlookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponse> EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.CheckUserOutlookAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest request) {
            return base.Channel.CheckUserOutlookAsync(request);
        }
        
        public System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookResponse> CheckUserOutlookAsync(string Username, string password) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.CheckUserOutlookRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.password = password;
            return ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).CheckUserOutlookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponse EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.IsAccountOutlookResult(EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest request) {
            return base.Channel.IsAccountOutlookResult(request);
        }
        
        public bool IsAccountOutlookResult(string Username, string password) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.password = password;
            EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponse retVal = ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).IsAccountOutlookResult(inValue);
            return retVal.Body.IsAccountOutlookResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponse> EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap.IsAccountOutlookResultAsync(EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest request) {
            return base.Channel.IsAccountOutlookResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultResponse> IsAccountOutlookResultAsync(string Username, string password) {
            EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest inValue = new EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequest();
            inValue.Body = new EVN.HCMC.WebAPI.DataProvider.WGISService.IsAccountOutlookResultRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.password = password;
            return ((EVN.HCMC.WebAPI.DataProvider.WGISService.wsGISSoap)(this)).IsAccountOutlookResultAsync(inValue);
        }
    }
}
